PROGRAM MAIN
    USE PARAMETERS
    USE MD
    IMPLICIT NONE
    REAL(KIND=8), DIMENSION(N, D) :: R, V, A ! A, A/S, A/S^2
    CHARACTER(LEN=2), DIMENSION(N) :: MOL_NAMES
    CHARACTER(LEN=2), DIMENSION(6) :: TYPES = ["He", "Ne", "Ar", "Kr", "Xe", "Rn"]
    REAL(KIND=8), DIMENSION(6) :: MASS_TYPES = [4.002602, 20.1797, 39.948, 83.798, 131.293, 222.0]
    REAL(KIND=8), DIMENSION(N) :: M ! AMU
    INTEGER :: I, J, K, START, FINISH, RATE, TYPE, NUM_MOLS, STAT
    INTEGER, DIMENSION(6) :: NUM_EACH
    REAL(KIND=8) :: TIME_ELAPSED, SYSTEM_TIME, TOTAL_PE, CURRENT_T

    CALL SYSTEM_CLOCK(COUNT_RATE=RATE)
    CALL SYSTEM_CLOCK(START)

    DO WHILE (SUM(NUM_EACH).LT.N)
        PRINT *, "SELECT TYPE OF MOLECULE"
        PRINT *, "1: HELIUM    2: NEON    3: ARGON    4: KRYPTON    5: XENON    6: RADON"
        READ(*, *, IOSTAT=STAT) TYPE
        IF (.NOT.ANY(TYPE.EQ.[1, 2, 3, 4, 5, 6])) THEN
            PRINT *, "INVALID"
            STOP
        END IF

        PRINT *, "SELECT NUMBER OF MOLECULES FOR THIS TYPE:"
        READ(*, *, IOSTAT=STAT) NUM_MOLS

        IF (NUM_MOLS.GT.(N - SUM(NUM_EACH))) THEN
            NUM_MOLS = N - SUM(NUM_EACH)
        END IF

        NUM_EACH(TYPE) = NUM_MOLS
        PRINT '(A, I0, A)', "ADDED ", NUM_EACH(TYPE), " MOLECULES"
        PRINT '(I0, A)', N - SUM(NUM_EACH), " MOLECULES REMAINING"
    END DO

    K = 1

    DO I = 1, SIZE(NUM_EACH)
        DO J = 1, NUM_EACH(I)
            MOL_NAMES(K) = TYPES(I)
            M(K) = MASS_TYPES(I)
            K = K + 1
        END DO
    END DO

    CALL RANDOM_NUMBER(R)
    CALL RANDOM_NUMBER(V)

    R = R * L
    V = (V * 100) - 50 ! GETTING MAXWELL DISTRIBUTIONS IS REALLY ANNOYING... SO I JUST RESCALE LATER

    TOTAL_PE = 0

    DO I = 1, N ! INITIALIZE ACCELERATION
        A(I, :) = DLJPOT(R, I, M) / M
    END DO
    
    DO I = 1, STEP_COUNT
        CALL VEL_VERLET(R, V, A, M) ! INTEGRATE BEFORE USING THERMOSTAT
        CURRENT_T = GET_T(V, M) ! FOR DUMP FILES
        ! CALL RESCALE_V(V, M)
        PRINT '(A, F10.6, A, I0)', "T = ", DT * I
        PRINT '(A, I0)', "STEP = ", I

        DO J = 1, N
            TOTAL_PE = TOTAL_PE + LJPOT(R, J)
        END DO
        CALL DUMP(MOL_NAMES, R, V, A, TOTAL_PE, CURRENT_T, DT * I, I)
        TOTAL_PE = 0
    END DO

    CALL SYSTEM_CLOCK(FINISH)
    TIME_ELAPSED = REAL(FINISH - START)/ REAL(RATE)
    SYSTEM_TIME = DT * STEP_COUNT

    PRINT *, 'ELAPSED TIME: ', TIME_ELAPSED, ' S'
    PRINT *, 'SYSTEM TIME: ', SYSTEM_TIME, ' PS'

END PROGRAM MAIN