PROGRAM MAIN
    USE PARAMETERS
    USE MD
    IMPLICIT NONE
    REAL(KIND=8), DIMENSION(N, D) :: R, V, A ! A, A/S, A/S^2
    CHARACTER(LEN=2), DIMENSION(N) :: MOL_NAMES
    REAL(KIND=8), DIMENSION(N) :: M ! MASSES
    INTEGER :: I, J, START, FINISH, RATE
    REAL(KIND=8) :: TIME_ELAPSED, SYSTEM_TIME, TOTAL_PE, CURRENT_T

    CALL SYSTEM_CLOCK(COUNT_RATE=RATE)
    CALL SYSTEM_CLOCK(START)

    M = 39.948

    MOL_NAMES = "Ar"

    CALL RANDOM_NUMBER(R)
    CALL RANDOM_NUMBER(V)

    R = R * L
    V = (V * 100) - 50 ! GETTING MAXWELL DISTRIBUTIONS IS REALLY ANNOYING... SO I JUST RESCALE LATER

    TOTAL_PE = 0

    DO I = 1, N ! INITIALIZE ACCELERATION
        A(I, :) = DLJPOT(R, I, M) / M
    END DO
    
    DO I = 1, STEP_COUNT
        CALL VEL_VERLET(R, V, A, M) ! INTEGRATE BEFORE USING THERMOSTAT
        CURRENT_T = GET_T(V, M) ! FOR DUMP FILES
        CALL RESCALE_V(V, M)
        PRINT '(A, F10.6, A, I0)', "T = ", DT * I
        PRINT '(A, I0)', "STEP = ", I

        DO J = 1, N
            TOTAL_PE = TOTAL_PE + LJPOT(R, J)
        END DO
        CALL DUMP(MOL_NAMES, R, V, A, TOTAL_PE, CURRENT_T, DT * I, I)
        TOTAL_PE = 0
    END DO

    CALL SYSTEM_CLOCK(FINISH)
    TIME_ELAPSED = REAL(FINISH - START)/ REAL(RATE)
    SYSTEM_TIME = DT * STEP_COUNT

    PRINT *, 'ELAPSED TIME: ', TIME_ELAPSED, ' S'
    PRINT *, 'SYSTEM TIME: ', SYSTEM_TIME, ' PS'

END PROGRAM MAIN